### PR TITLE
Added reponsiveness to home page

### PR DESCRIPTION
**Pull request by drockparashar**

### CODE REVIEW

**Comment by drockparashar** [comment]
Please merge this pull request so that I can start working on other issues.

**Comment by Gaurav-Verma07** [comment]
bro this section is still not looking well:
image
make these boxes in stack

**Comment by drockparashar** [comment]
okay

**Comment by drockparashar** [comment]
I have added responsiveness to 3 pages that were assigned to me in 3 separate issues, please look into it.

image

image

image

**Comment by drockparashar** [comment]
Please review this pull request.

**Comment by Gaurav-Verma07** [comment]
Br

**Comment by drockparashar** [comment]
Hey, I have completed issue #3 , #4 , #5 that were assigned to me in this pull request. So you can close them and please award me the points.

**Comment by drockparashar** [comment]
Hey, I have completed issue #3 , #4 , #5 that were assigned to me in this pull request. So you can close them and please award me the points .

**Comment by Gaurav-Verma07** [comment]
Since you completed 3 issues in this single PR, so I'm labeling it as `HARD`

**Pull request merged**
